extends Node

class_name XML

var data = ""
var header = ""

func _init(header, attrs=null):
	data += "<!-- THIS WAS AUTOGENERATED BY RDFTINKER! BEWARE THE GREAT MESSY! -->\n"
	add_element(header, true, attrs)
	self.header = header
	
func add_element(head, open=true, attrs=null):
	data += "<" + head
	if(attrs != null):
		data += " "
		for attr in attrs:
			data += attr + "=\"" + attrs[attr] + "\" "
	if(not open):
		data += "/>"
	else: data += ">"

func close_element(head):
	data += "</" + head + ">"

func add_text(txt):
	data += txt
	
func finish_and_save(path):
	close_element(header)
	var file = FileAccess.open(path, FileAccess.WRITE)
	file.store_buffer(RDF.encode_bytes(data))
